default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: aaronbrown
  password: <%= ENV['DATABASE_PASSWORD'] %> # Use ENV variable for security
  host: localhost

development:
  <<: *default
  database: test_app_1_development

test:
  <<: *default
  database: test_app_1_test


# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_URL'] %>
  
cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
